foosh/cart/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

import cart.views


__all__ = []


app_name = "cart"

urlpatterns = [
    path(
        "",
        cart.views.CartView.as_view(),
        name="cart",
    ),
    path(
        "update_item_in_cart/",
        cart.views.UpdateItemInCart.as_view(),
        name="update_item_in_cart",
    ),
    path(
        "checkout/",
        cart.views.CheckoutView.as_view(),
        name="checkout",
    ),
    path(
        "order_update/",
        csrf_exempt(cart.views.OrderUpdateView.as_view()),
        name="order_update",
    ),
]

foosh/catalog/urls.py
from django.urls import path, register_converter

from catalog import converters, views


register_converter(converters.CategoryConverter, "category")

app_name = "catalog"

urlpatterns = [
    path(
        "",
        views.NoCategoryRedirectView.as_view(),
        name="redirect",
    ),
    path(
        "<category:category>/",
        views.ItemListView.as_view(),
        name="category",
    ),
    path(
        "item/<int:pk>/",
        views.ItemDetailView.as_view(),
        name="item",
    ),
]

foosh/foosh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
]

if settings.DEBUG:
    urlpatterns += (
        path(
            "__debug__/",
            include("debug_toolbar.urls"),
        ),
    )

if settings.MEDIA_ROOT:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=(settings.MEDIA_ROOT),
    )

foosh/homepage/urls.py
from django.urls import path

import homepage.views

__all__ = []


app_name = "homepage"

urlpatterns = [
    path(
        "",
        homepage.views.Home.as_view(),
        name="home",
    ),
]

foosh/users/urls.py
from django.contrib.auth import views
from django.urls import path

import users.forms
import users.views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            authentication_form=users.forms.CustomAuthForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            form_class=users.forms.CustomPasswordChangeForm,
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            form_class=users.forms.CustomPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "signup/",
        users.views.SignUpView.as_view(),
        name="signup",
    ),
    path(
        "signup/student/",
        users.views.StudentSignUpView.as_view(),
        name="student_signup",
    ),
    path(
        "signup/school/",
        users.views.SchoolSignUpView.as_view(),
        name="school_signup",
    ),
    path(
        "load_schools/",
        users.views.LoadSchools.as_view(),
        name="load_schools",
    ),
    path(
        "profile/<str:nav>",
        users.views.ProfileView.as_view(),
        name="profile",
    ),
]

foosh/templates/includes/card.html
{% load static %}
<div class="card">
	{% if item.image %}
		<a href="{% url 'catalog:item' item.id %}">
			<img src="{{ item.image.url }}" alt="item-img" class="item-img">
		</a>
	{% endif %}
	<div class="item-info">
		<div class="favorites">
			<p class="price">{{ item.price }}₽</p>
			<svg id="heart" class="heart" onclick="rate('heart', 1)" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#000000"><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>
		</div>
		<p class="name">{{ item.name }}</p>
		<div class="stars">
			<img src="{% static '/imgs/catalog/star.svg' %}" class="star">
			<img src="{% static '/imgs/catalog/star.svg' %}" class="star">
			<img src="{% static '/imgs/catalog/star.svg' %}" class="star">
			<img src="{% static '/imgs/catalog/star.svg' %}" class="star">
			<img src="{% static '/imgs/catalog/star.svg' %}" class="star">
		</div>
		<div class="buy-item">
			<div class="count-item" style="display:none"  data-id_of_count="{{ item.id }}.plus_minus_div">
				<button class="input update-cart" data-type_of_button="plus_minus" data-id_of_count="{{ item.id }}.minus" data-action="remove" data-product="{{ item.id }}" type="button" value="-">-</button>
				<button class="input" data-id_of_count="{{ item.id }}.count" type="text">0</button>
				<button class="input update-cart" data-type_of_button="plus_minus" data-id_of_count="{{ item.id }}.plus" data-action="add" data-product="{{ item.id }}" type="button" value="+">+</button>
			</div>
			<button class="btn-buy update-cart"  style="display:block" data-type_of_button="add_to_chart" data-id_of_count="{{ item.id }}.add" data-action="add" data-product="{{ item.id }}">В корзину</button>
		</div>
	</div>
</div>

foosh/templates/includes/footer.html
{% load static %}
<footer class="footer">
	<div class="footer-content">
		<div class="left-block-footer">
			<a href="#"><img src="{% static '/imgs/header/logo.svg' %}" alt="logo" class="logo"></a>
			<span>© 2024</span>
			<div class="navbar-footer">
				<a href="#" class="nav-item-footer">Поддержка</a>
				<a href="#" class="nav-item-footer">Правовая информация</a>
			</div>
		</div>
		<div class="right-block-footer">
			<a href="#" class="email">team4@django.com</a>
			<div class="link-icons">
				<a href="#"><img src="{% static 'imgs/footer/vk.svg' %}" alt="vkontakte" class="link-icons"></a>
				<a href="#"><img src="{% static 'imgs/footer/telegram.svg' %}" alt="telegram" class="link-icons"></a>
				<a href="#"><img src="{% static 'imgs/footer/facebook.svg' %}" alt="facebook" class="link-icons"></a>
			</div>
		</div>
	</div>
</footer>

foosh/templates/includes/form.html
{% if form.non_field_errors %}
  <div class="non-field-errors">
    {% for err in form.non_field_errors %}
      <p class="form-error">{{ err }}</p>
    {% endfor %}
  </div>
{% endif %}
{% for field in form %}
	{{ field }}
	{% for error in field.errors %}
		<div class="">
			{{ error|escape }}
		</div>
	{% endfor %}
	{% if field.help_text %}
		{{ field.help_text|safe }}
	{% endif %}
{% endfor %}

foosh/templates/includes/header.html
{% load static %}
<header class="header">
	<div class="header-content">
		<a href="{% url 'homepage:home' %}"><img src="{% static '/imgs/header/logo.svg' %}" alt="logo" class="logo"></a>
		<div class="navbar-header">
			<a href="{% url 'catalog:category' 1 %}" class="nav-item">Каталог</a>
			<a href="{% url 'homepage:home' %}" class="nav-item">О нас</a>
			<a href="{% url 'homepage:home' %}" class="nav-item">Контакты</a>
			{% if user.is_authenticated %}
				<div class="auth-user-header">
					<a href="{% url 'cart:cart' %}">
						<img src="{% static '/imgs/header/cart.svg' %}" alt="cart">
					</a>
					<div class="user-info">
						<a href="{% url 'users:profile' 'menu' %}" class="username">
							{{ user.email }}
						</a>
						<a href="{% url 'users:logout' %}">
							<img src="{% static '/imgs/header/logout.svg' %}" alt="logout" class="logout">
						</a>
					</div>
				</div>
		{% else %}
			<a href="{% url 'users:login' %}" class="btn-login">Войти</a>
		{% endif %}
		</div>
	</div>
</header>