foosh/cart/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

import cart.views


__all__ = []


app_name = "cart"

urlpatterns = [
    path(
        "",
        cart.views.CartView.as_view(),
        name="cart",
    ),
    path(
        "update_item_in_cart/",
        cart.views.UpdateItemInCart.as_view(),
        name="update_item_in_cart",
    ),
    path(
        "checkout/",
        cart.views.CheckoutView.as_view(),
        name="checkout",
    ),
    path(
        "order_update/",
        csrf_exempt(cart.views.OrderUpdateView.as_view()),
        name="order_update",
    ),
]

foosh/foosh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
]

if settings.DEBUG:
    urlpatterns += (
        path(
            "__debug__/",
            include("debug_toolbar.urls"),
        ),
    )

if settings.MEDIA_ROOT:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=(settings.MEDIA_ROOT),
    )

foosh/cart/models.py
from django.db import models

from catalog.models import Item
from users.models import CustomUser, School, Student


__all__ = []


class Cart(models.Model):
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="carts",
        verbose_name="корзина",
    )


class CartItem(models.Model):
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        related_name="items",
        verbose_name="товар",
    )

    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        related_name="cartitems",
        verbose_name="однотоварная корзина",
    )

    quantity = models.IntegerField(
        "количество",
        default=0,
    )

    def __str__(self):
        return f"{self.item.name} (x{self.quantity})"


class Status(models.IntegerChoices):
    CREATED = 1, "Создан"
    PAID = 2, "Оплачен"
    READY = 3, "Готов"
    CANCELLED = 4, "Отменен"


class Order(models.Model):
    user = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        verbose_name="пользователь",
        related_name="orders",
    )

    school = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        verbose_name="школа",
        related_name="orders",
    )

    total_price = models.DecimalField(
        "итого",
        max_digits=10,
        decimal_places=2,
        default=0.0,
    )

    status = models.IntegerField(
        "статус",
        choices=Status.choices,
        default=Status.CREATED,
    )

    payment = models.CharField(
        "платеж",
        max_length=255,
    )

    created_at = models.DateTimeField(
        "создано",
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        "изменено",
        auto_now=True,
    )

    def __str__(self):
        return f"Заказ №{self.pk}"

    def save(self, *args, **kwargs):
        if self.pk:
            self.total_price = sum(
                item.item.price * item.quantity for item in self.items.all()
            )

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы"


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        verbose_name="заказ",
        related_name="items",
    )

    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        verbose_name="товар",
    )

    quantity = models.PositiveIntegerField(
        "количество",
        default=0,
    )

    class Meta:
        unique_together = ("order", "item")

foosh/cart/views.py
import json

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView
from yookassa import Payment
from yookassa.domain.common import SecurityHelper
from yookassa.domain.notification import (
    WebhookNotificationEventType,
    WebhookNotificationFactory,
)

from cart.models import Cart, CartItem, Order, OrderItem, Status
from cart.utils import get_client_ip
from catalog.models import Item


__all__ = []


class CartView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy("users:login")
    template_name = "cart/cart.html"
    context_object_name = "cartitems"
    model = CartItem

    def get_queryset(self):
        cart, _ = Cart.objects.get_or_create(user=self.request.user)
        return self.model.objects.filter(cart=cart)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Корзина"
        return context


class UpdateItemInCart(LoginRequiredMixin, View):
    login_url = reverse_lazy("users:login")

    def post(self, request, *args, **kwargs):
        data = json.loads(self.request.body)
        product_id = data["product_id"]
        action = data["action"]

        item = Item.objects.get(id=product_id)
        cart, cart_created = Cart.objects.get_or_create(
            user=request.user,
        )
        cart_item, cart_item_created = CartItem.objects.get_or_create(
            cart=cart,
            item=item,
        )

        if action == "add":
            cart_item.quantity += 1
        elif action == "remove":
            cart_item.quantity -= 1

        cart_item.save()

        if cart_item.quantity <= 0:
            cart_item.delete()

        return JsonResponse("Item was added", safe=False)


class CheckoutView(LoginRequiredMixin, View):
    login_url = reverse_lazy("users:login")

    def get(self, request, *args, **kwargs):
        cart, created = Cart.objects.get_or_create(
            user=self.request.user,
        )
        if created or CartItem.objects.filter(cart=cart).count() == 0:
            return redirect("cart:cart")

        order = Order.objects.create(
            user=request.user.student,
            school=request.user.student.school,
        )
        order.save()

        for i in CartItem.objects.filter(cart=cart):
            OrderItem.objects.create(
                order=order,
                item=i.item,
                quantity=i.quantity,
            )

        order.save()

        cart.delete()

        res = Payment.create(
            {
                "amount": {
                    "value": order.total_price,
                    "currency": "RUB",
                },
                "confirmation": {
                    "type": "redirect",
                    "return_url": settings.YOKASSA_SUCCESS_URL,
                },
                "capture": True,
                "description": f"Заказ №{order.pk}",
                "metadata": {
                    "orderNumber": order.pk,
                },
                "test": "test",
            },
        )

        payment_url = res.confirmation.confirmation_url
        order.payment = payment_url
        order.save()

        return redirect(res.confirmation.confirmation_url)


class OrderUpdateView(View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        ip = get_client_ip(request)
        if not SecurityHelper().is_ip_trusted(ip):
            return HttpResponse(status=400)

        event_json = json.loads(request.body)
        try:
            notification_object = WebhookNotificationFactory().create(
                event_json,
            )
            response_object = notification_object.object

            if (
                notification_object.event
                == WebhookNotificationEventType.PAYMENT_SUCCEEDED
            ):
                order = Order.objects.get(
                    pk=response_object.metadata.get("orderNumber"),
                )
                status = Status.PAID

            elif (
                notification_object.event
                == WebhookNotificationEventType.PAYMENT_CANCELED
            ):
                order = Order.objects.get(
                    pk=response_object.metadata.get("orderNumber"),
                )
                status = Status.CANCELLED

            else:
                return HttpResponse(status=400)

            order.status = status
            order.save()

        except Exception:
            return HttpResponse(status=400)

        return HttpResponse(status=200)

foosh/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/cart/cart.css' %}">
  <main class="cart">
    <div class="cart-content">
      <div class="left-block">
        <div class="cart-titles">
          <h1 class="cart-title">Ваша корзина</h1>
          <p class="count-items">{{ cartitems.count }} товар(ов)</p>
        </div>
        <div class="items">
          {% for cartitem in cartitems %}
            <div class="item">
              <img src="{{ cartitem.item.image.url }}" alt="{{ cartitem.item.name }}" class="item-img">
              <div class="item-info">
                <div class="item-main-info">
                  <h2 class="item-name">{{ cartitem.item.name }}</h2>
                  <h2 class="item-price">{{ cartitem.item.price }}₽</h2>
                </div>
                <h3 class="item-category">{{ cartitem.item.get_category_display }}</h3>
                <div class="counts-item">
                  <div class="counts-item-content">
                    <h3 class="count-text">количество</h3>
                    <div class="buy-item">
                      <div class="count-item" style="display:flex" data-id_of_count="{{ cartitem.item.id }}.plus_minus_div">
                        <button class="input update-cart" data-type_of_button="plus_minus" data-id_of_count="{{ cartitem.item.id }}.minus" data-action="remove" data-product="{{ cartitem.item.id }}" type="button" value="-">-</button>
                        <button class="input" data-id_of_count="{{ cartitem.item.id }}.count" type="text">{{ cartitem.quantity }}</button>
                        <button class="input update-cart" data-type_of_button="plus_minus" data-id_of_count="{{ cartitem.item.id }}.plus" data-action="add" data-product="{{ cartitem.item.id }}" type="button" value="+">+</button>
                      </div>
                      <button class="btn-buy update-cart" style="display:none" data-type_of_button="add_to_chart" data-id_of_count="{{ item.id }}.add" data-action="add" data-product="{{ item.id }}">В корзину</button>
                    </div>
                  </div>
                  <div class="item-icons">
                    <a href=""><img src="{% static '/imgs/cart/heart.png' %}" alt="" class="heart"></a>
                    <a href=""><img src="{% static '/imgs/cart/brush.png' %}" alt="" class="brush"></a>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="buy-block">
        <div class="price-info">
          <p class="itog-text">Итого</p>
          <p class="result-price">...₽</p>
        </div>
        <a href="{% url 'cart:checkout' %}" class="btn-place-order">Оформить заказ</a>
      </div>
    </div>
  </main>
  <script src="{% static '/js/change_add_to_cart.js' %}"></script>
	<script src="{% static '/js/cart_add_delete.js' %}"></script>
{% endblock %}