foosh/cart/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

import cart.views


__all__ = []


app_name = "cart"

urlpatterns = [
    path(
        "",
        cart.views.CartView.as_view(),
        name="cart",
    ),
    path(
        "update_item_in_cart/",
        cart.views.UpdateItemInCart.as_view(),
        name="update_item_in_cart",
    ),
    path(
        "checkout/",
        cart.views.CheckoutView.as_view(),
        name="checkout",
    ),
    path(
        "order_update/",
        csrf_exempt(cart.views.OrderUpdateView.as_view()),
        name="order_update",
    ),
]

foosh/foosh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
]

if settings.DEBUG:
    urlpatterns += (
        path(
            "__debug__/",
            include("debug_toolbar.urls"),
        ),
    )

if settings.MEDIA_ROOT:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=(settings.MEDIA_ROOT),
    )

foosh/users/urls.py
from django.contrib.auth import views
from django.urls import path

import users.forms
import users.views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            authentication_form=users.forms.CustomAuthForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            form_class=users.forms.CustomPasswordChangeForm,
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            form_class=users.forms.CustomPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "signup/",
        users.views.SignUpView.as_view(),
        name="signup",
    ),
    path(
        "signup/student/",
        users.views.StudentSignUpView.as_view(),
        name="student_signup",
    ),
    path(
        "signup/school/",
        users.views.SchoolSignUpView.as_view(),
        name="school_signup",
    ),
    path(
        "load_schools/",
        users.views.LoadSchools.as_view(),
        name="load_schools",
    ),
    path(
        "profile/<str:nav>",
        users.views.ProfileView.as_view(),
        name="profile",
    ),
]

foosh/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from users.managers import CustomUserManager


__all__ = []


class CustomUser(AbstractUser):
    username = None

    email = models.EmailField(
        unique=True,
    )

    is_student = models.BooleanField(
        "ученик",
        default=False,
    )

    is_school = models.BooleanField(
        "школа",
        default=False,
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class School(models.Model):
    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        primary_key=True,
        verbose_name="пользователь",
    )

    name = models.CharField(
        "название",
        max_length=255,
        blank=False,
    )

    city = models.ForeignKey(
        "cities_light.City",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="город",
    )

    class Meta:
        verbose_name = "школа"
        verbose_name_plural = "школы"

    def __str__(self):
        return f"{self.name} ({self.city})"


class Student(models.Model):
    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        primary_key=True,
        verbose_name="пользователь",
    )

    name = models.CharField(
        "имя",
        max_length=100,
        blank=False,
    )

    surname = models.CharField(
        "фамилия",
        max_length=100,
        blank=False,
    )

    patronymic = models.CharField(
        "отчество",
        max_length=100,
    )

    city = models.ForeignKey(
        "cities_light.City",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="город",
    )

    school = models.ForeignKey(
        School,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="школа",
    )

    def __str__(self):
        return f"{self.name} {self.surname} {self.patronymic}"

    class Meta:
        verbose_name = "ученик"
        verbose_name_plural = "ученики"

foosh/users/forms.py
from cities_light.models import City
from django import forms
from django.contrib import auth
from django.forms import widgets
from django_recaptcha.fields import ReCaptchaField

from users.models import CustomUser, School, Student


__all__ = []


class StylesFormMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            if field.html_name != "captcha":
                field.field.widget.attrs["class"] = "input"


class CustomAuthForm(auth.forms.AuthenticationForm):
    username = forms.EmailField(
        widget=widgets.EmailInput(attrs={"placeholder": "Почта"}),
    )
    password = forms.CharField(
        widget=widgets.PasswordInput(
            attrs={"placeholder": "Пароль"},
        ),
    )
    captcha = ReCaptchaField()


class CustomPasswordChangeForm(auth.forms.PasswordChangeForm):
    old_password = forms.CharField(
        widget=widgets.PasswordInput(attrs={"placeholder": "Старый пароль"}),
    )
    new_password1 = forms.CharField(
        widget=widgets.PasswordInput(attrs={"placeholder": "Новый пароль"}),
    )
    new_password2 = forms.CharField(
        widget=widgets.PasswordInput(
            attrs={"placeholder": "Подтвердите новый пароль"},
        ),
    )


class CustomPasswordResetForm(auth.forms.PasswordResetForm):
    email = forms.CharField(
        widget=widgets.EmailInput(attrs={"placeholder": "Почта"}),
    )


class CustomUserCreationForm(auth.forms.UserCreationForm):
    email = forms.EmailField(
        widget=widgets.EmailInput(attrs={"placeholder": "Почта"}),
    )
    password1 = forms.CharField(
        widget=widgets.PasswordInput(attrs={"placeholder": "Пароль"}),
    )
    password2 = forms.CharField(
        widget=widgets.PasswordInput(
            attrs={"placeholder": "Повторите пароль"},
        ),
    )


class StudentSignUpForm(StylesFormMixin, CustomUserCreationForm):
    name = forms.CharField(
        max_length=100,
        label="Имя",
        required=True,
        widget=widgets.TextInput(
            attrs={"placeholder": "Имя"},
        ),
    )

    surname = forms.CharField(
        max_length=100,
        label="Фамилия",
        required=True,
        widget=widgets.TextInput(
            attrs={"placeholder": "Фамилия"},
        ),
    )

    patronymic = forms.CharField(
        max_length=100,
        label="Отчество",
        widget=widgets.TextInput(
            attrs={"placeholder": "Отчество"},
        ),
    )

    city = forms.ModelChoiceField(
        queryset=City.objects.all(),
        to_field_name="id",
        label="Город",
        empty_label="Выберите город",
        required=True,
        widget=widgets.Select(
            attrs={
                "placeholder": "Город",
                "hx-get": "/auth/load_schools/",
                "hx-target": "#id_school",
            },
        ),
    )

    school = forms.ModelChoiceField(
        queryset=School.objects.none(),
        label="Школа",
        empty_label="Выберите школу",
        required=True,
        widget=widgets.Select(
            attrs={
                "placeholder": "Школа",
            },
        ),
    )

    captcha = ReCaptchaField()

    class Meta(auth.forms.UserCreationForm.Meta):
        model = CustomUser
        fields = (
            CustomUser.email.field.name,
            "name",
            "surname",
            "patronymic",
            "city",
            "school",
            "captcha",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if "city" in self.data:
            city_id = int(self.data.get("city"))
            self.fields["school"].queryset = School.objects.filter(
                city_id=city_id,
            )

    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        Student.objects.create(
            user=user,
            name=self.cleaned_data.get("name"),
            surname=self.cleaned_data.get("surname"),
            patronymic=self.cleaned_data.get("patronymic"),
            city=self.cleaned_data.get("city"),
            school=self.cleaned_data.get("school"),
        )
        return user


class SchoolSignUpForm(StylesFormMixin, CustomUserCreationForm):
    name = forms.CharField(
        max_length=255,
        label="Название",
        required=True,
        widget=widgets.TextInput(
            attrs={"placeholder": "Название"},
        ),
    )

    city = forms.ModelChoiceField(
        queryset=City.objects.all(),
        label="Город",
        empty_label="Выберите город",
        required=True,
        widget=widgets.Select(
            attrs={"placeholder": "Город"},
        ),
    )

    captcha = ReCaptchaField()

    class Meta(auth.forms.UserCreationForm.Meta):
        model = CustomUser
        fields = (
            CustomUser.email.field.name,
            "name",
            "city",
            "captcha",
        )

    def save(self):
        user = super().save(commit=False)
        user.is_school = True
        user.save()
        School.objects.create(
            user=user,
            name=self.cleaned_data.get("name"),
            city=self.cleaned_data.get("city"),
        )
        return user

foosh/users/views.py
from cities_light.models import City
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views.generic import CreateView, TemplateView, View

from cart.models import Order
import users.forms
from users.models import CustomUser, School, Student


__all__ = []


class SignUpView(TemplateView):
    template_name = "users/signup.html"


class StudentSignUpView(CreateView):
    model = CustomUser
    form_class = users.forms.StudentSignUpForm
    template_name = "users/student_signup.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "student"
        kwargs["cities"] = City.objects.all()
        kwargs["schools"] = School.objects.all()
        kwargs["title"] = "Регистрация"

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)

        return redirect("/")


class SchoolSignUpView(CreateView):
    model = CustomUser
    form_class = users.forms.SchoolSignUpForm
    template_name = "users/school_signup.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "school"
        kwargs["title"] = "Регистрация"

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)

        return redirect("/")


class LoadSchools(TemplateView):
    template_name = "users/school_options.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city_id = self.request.GET.get("city")
        schools = School.objects.filter(city_id=city_id)
        context["schools"] = schools

        return context


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, nav, *args, **kwargs):
        if request.user.is_student:
            template_name = "users/student_profile.html"

            user = Student.objects.filter(user_id=request.user.id).first()
            user_orders = Order.objects.filter(user=user).order_by(
                "-created_at",
            )

            context = {
                "orders": user_orders,
                "title": "Личный кабинет",
            }

            return render(request, template_name, context)

        if request.user.is_school:
            if nav == "orders":
                template_name = "users/school_profile_orders.html"

                school = School.objects.filter(user_id=request.user.id).first()
                user_orders = Order.objects.filter(school=school).order_by(
                    "-created_at",
                )

                context = {
                    "orders": user_orders,
                    "title": "Список заказов",
                }

                return render(request, template_name, context)

            if nav == "menu":
                template_name = "users/school_profile_menu.html"

                context = {
                    "title": "Список товаров",
                }

                return render(request, template_name, context)

        return redirect("users:signup")

foosh/templates/users/login.html
{% extends "base2.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/users/login.css' %}">
  <body style="background-image: url('{% static '/imgs/users/bg_login.svg' %}')">
    <div class="bg-form">
      <img src="{% static '/imgs/users/logo.svg' %}" alt="logo" class="logo">
      <h1 class="title">Войдите в личный кабинет</h1>
      <form method="post" action="" class="form" style="background-image: url('{% static '/imgs/users/bg_log-card.svg' %}')">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <button type="submit" class="btn-signin">Войти</button>
        <a href="{% url 'users:signup' %}" class="link">Нет аккаунта?</a>
        <a href="{% url 'users:password_reset' %}" class="link">Забыли пароль?</a>
      </form>
    </div> 
  </body>
{% endblock %}

foosh/templates/users/logout.html
{% extends "base.html" %}
{% block content %}
  <h2>Вы успешно вышли</h2>
{% endblock %}

foosh/templates/users/password_change.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/users/password.css' %}">
  <main class="main" style="background-image: url('{% static '/imgs/users/bg_login.svg' %}')">
    <form method="post" class="form">
      <h2>Изменить пароль</h2>
      {% csrf_token %}
      {% include "includes/form.html" %}
      <br>
      <button class="btn btn-primary" type="submit">Подтверить</button>
    </form>
  </main>
{% endblock %}

foosh/templates/users/password_change_done.html
{% extends "base.html" %}
{% block content %}
  <h2>Пароль успешно изменен</h2>
{% endblock %}

foosh/templates/users/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/users/password.css' %}">
  <main class="main" style="background-image: url('{% static '/imgs/users/bg_login.svg' %}')">
    <form method="post" class="form">
      <h2>Сбросить пароль</h2>
      {% csrf_token %}
      {% include "includes/form.html" %}
      <br>
      <button class="btn" type="submit">Подтверить</button>
    </form>
  </main>
{% endblock %}

foosh/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
  <h2>Пароль успешно изменен</h2>
{% endblock %}

foosh/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <h2>Восстановить пароль</h2>
  <form method="post">
    {% csrf_token %}
    {% include "includes/form.html" %}
    <br>
    <button class="btn btn-primary" type="submit">Подтверить</button>
  </form>  
{% endblock %}

foosh/templates/users/password_reset_done.html
{% extends "base2.html" %}
{% block content %}
  <h2>Вы успешно сбросили пароль</h2>
{% endblock %}

foosh/templates/users/school_options.html
{% for school in schools %}
  <option value="{{ school.user_id }}">{{ school.name }}</option>
{% endfor %}

foosh/templates/users/school_profile_menu.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/users/school_profile_menu.css' %}">
  <main class="menu-school">
    {% include "includes/users/profile-info.html" %}
    <section class="menu-info">
      {% include "includes/users/navbar-profile.html" %}
      <div class="main-menu-info">
        <div class="category-navbar">
          <a href="" class="category-navbar-item">Выпечка</a>
          <a href="" class="category-navbar-item">Горячее</a>
          <a href="" class="category-navbar-item">Напитки</a>
          <a href="" class="category-navbar-item">Комбо</a>
          <a href="" class="btn-add-item">Добавить товар</a>
          <a href="" class="btn-edit-menu">Редактировать меню</a>
        </div>
        {% if items %}
          <div class="cards">
            {% for item in items %}
              {% include "includes/card.html" %}
            {% endfor %}
          </div>
        {% else %}
          <h1 class="no-items">В данный момент каталог товаров пуст</h1>
        {% endif %}
      </div>
    </section>
  </main>
{% endblock %}

foosh/templates/users/school_profile_orders.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/users/school_profile_orders.css' %}">
  <main class="personal-account">
    {% include "includes/users/profile-info.html" %}
    <section class="orders">
      {% include "includes/users/navbar-profile.html" %}
      <div class="ordes-items">
        {% include "includes/users/orders.html" %}
      </div>
    </section>
  </main>
  <script src="{% static '/js/school_profile_orders.js' %}"></script>
{% endblock %}

foosh/templates/users/school_signup.html
{% extends "base2.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/users/signup2.css' %}">
  <body style="background-image: url('{% static '/imgs/users/bg_login.svg' %}')">
    <div class="bg-form">
      <img src="{% static '/imgs/users/logo.svg' %}" alt="logo" class="logo">
      <h1 class="title">Регистрация</h1>
      <form method="post" action="" class="form">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <button type="submit" class="btn-signup">Зарегистрироваться</button>
      </form>
      <a href="{% url 'users:login' %}" class="link">Уже есть аккаунт?</a>
    </div>
  </body>
{% endblock %}

foosh/templates/users/student_profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/users/student_profile.css' %}">
  <main class="student-profile">
    <h1 class="student-profile-title">Личный кабинет</h1>
    <div class="student-info">
      <div class="student-main-info">
        <h1 class="student-name">{{ user.student.surname }} {{ user.student.name }} {{ user.student.patronymic }}</h1>
        <p class="student-field"><b>Учебное заведение:</b> {{ user.student.school.name }}</p>
        <p class="student-field"><b>Город:</b> {{ user.student.city.name }}</p>
        <p class="student-field"><b>Почта:</b> {{ user.email }}<p>
        <div class="btns-edit">
          <a href="" class="btn-edit btn-edit-profile">Редактировать профиль</a>
          <a href="{% url 'users:password_change' %}" class="btn-edit btn-edit-password">Изменить пароль</a>
        </div>
      </div>
      <div class="student-orders">
        <h1>Заказы</h1>
        <div class="student-order">
          {% include "includes/users/orders.html" %}
        </div>
      </div>
    </div>
  </main>
  <script src="{% static '/js/school_profile_orders.js' %}"></script>
{% endblock %}

foosh/templates/users/student_signup.html
{% extends "base2.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/users/signup2.css' %}">
  <script src="https://unpkg.com/htmx.org@1.9.11" integrity="sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0" crossorigin="anonymous"></script>
  <body style="background-image: url('{% static '/imgs/users/bg_login.svg' %}')">
    <div class="bg-form">
      <img src="{% static '/imgs/users/logo.svg' %}" alt="logo" class="logo">
      <h1 class="title">Регистрация</h1>
      <form method="post" action="" class="form">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <button type="submit" class="btn-signup">Зарегистрироваться</button>
      </form>
      <a href="{% url 'users:login' %}" class="link">Уже есть аккаунт?</a>
    </div>
  </body>
{% endblock %}